### PR TITLE
decrypt and encrypt now raises exception, fixes #2

### LINKED ISSUE #2: Compilation errors with Nim 0.19
Does not compile with Nim 0.19 because of nil string returns.

### PR DESCRIPTION
**Pull request by enthus1ast**

### CODE REVIEW

**Comment by enthus1ast** [comment]
what would you prefer: return empty strings or raise exception?

**Comment by andot** [comment]
Raises exception is incompatible with other language implementation. So it is not a good idea.
