### ISSUE TITLE
Compilation errors with Nim 0.19

### ISSUE THREAD

**Issue by janicetr** [xxtea/xxtea-nim#2]
Does not compile with Nim 0.19 because of nil string returns.
